#########################################################
#                                                       #
#   Flex V3 ➤ Minecraft AntiCheat ➤ AntiAura Edition    #
#                                                       #
#   Plugin Name: AntiAura (AA)                          #
#   Plugin Developer: joehot200                         #
#   Plugin Link: http://bit.ly/2tUY9Ur                  #
#   Config based on version: 10.95                      #
#   Config configurator: ItsMennyo                      #
#   Version: BUILD 1.4.214 BETA                         #
#   Page/Download: http://bit.ly/2tQjMVe                #
#                                                       #
#   Copyright © 2017 ItsMennyo, The Netherlands         #
#                                                       #
#########################################################

DisableElytraChecks: true
ConsoleLogDragbacks: true

Violations:
  ExecuteAllCommands: false
  ViolationDecreasePerHour: 0
  2: tempban %PLAYER% 10m
  5: ban %PLAYER% You have been banned for using the %HACKNAME% hack %HACKAMOUNT% times!

PingAccounting:
 #This check ensures that players do not fake their ping.
 #Default: true
  Enabled: true
  #If you have a country-based server, the host is also in the same country, you can leave it at 100. If your server is playing worldwide, you need to increase it.
  #Default: 150
  PingLeniency: 100
  SilenceWarnings: false
  UseRealPing: false
  #What is the maximum allowed ping before false positives comes?
  #Default: 600
  MaxPing: 500

Forcefield:
 #The Forcefield check works as several KillAura checks that work together for the best detection.
  Angle:
    Enabled: false
    HackingAngle: 1.8
    BlockImpossibleHits: true
    Threshold: 8
    SafeHitDecrease: 1.0
    AngleCommand: kick %PLAYER% Killaura is not allowed!#broadcast %PLAYER% was kicked for hacking! (Killaura)(An)
  Reach:
   #Reach check ensures that players can not hit entities too far.
   #Default: true
    Enabled: true
    MaxReach: 4.5
  HeadMove:
    Enabled: false
    CancelExtremeMovement: true
    LagBackThreshold: 3.0
    MaxMove: 0.08
    CancelMove:
      CancelMove: 0.15
      UseHeadMoveThreshold: true
      MinimumBlockThreshold: 2
    CantAttackTime: 5
    Threshold: 8
    SafeHitDecrease: 0.65
    DecreasePerSecond: 1.0
    HeadCommand: kick %PLAYER% Killaura is not allowed!#broadcast %PLAYER% was kicked for hacking! (Killaura)(H)
  Accuracy:
   #Accuracy check checks how many hits are performed on an entity.
   #Default: true
    Enabled: true
    IsMoving: 0.025
    IsMoving2: 0.0050
    MovingAttackTime: 8
    DistanceAccounting:
      Enabled: true
      DistanceAmount: 3.5
      DistanceWeight: 0.20
    YawOnly: true
    Threshold: 8
    ArmSwingDecrease: 0.25
    DecreasePerSecond: 0.10
    #Here you can customize the command that is executed when a player is kicked by this check.
    #Default: kick %PLAYER% Accuracy
    AccuracyCommand: kick %PLAYER% Accuracy

FastClick:
 #FastClick check checks the constant click speeds a player performs.
 #Default: true
  Enabled: true
  Threshold: 5
  MaxClicksPerSecond: 15
  LagAccounting: true
  #Here you can customize the command that is executed when a player is kicked by this check.
  #Default: kick %PLAYER% FastClick
  FastClickCommand: kick %PLAYER% FastClick

AutoBow:
  Enable: false
  BowThreshhold: 3
  BlockArrowsIfSpeedTooHigh: true
  AutoBowCommand: kick %PLAYER% AutoBow is not allowed!#broadcast %PLAYER% was kicked for hacking! (AutoBow)

Soup:
  Enabled: false
  SoupTime: 1

Map:
  MapScrewer: false
  LenientMode: true
  DistanceChecked: 50
  DistanceCheckedY: 30
  HowOften: 10
  MinDistance: 10
  HideOnlyPlayers: false
  HidePlayersThroughBlocks: true
  HidePlayersBehind: true
  TileESP:
    Enabled: false
    ShowDistance: 15
    TracerDistance: 60
    IntervalMult: 1
    SuperLenientMode: false
    ChunkDistance: 5
  XRay:
    Enabled: false
    IntervalMult: 20
    ShowDistance: 20
    TracerDistance: 60
    ChunkDistance: 5

Knockback:
  Enabled: false
  TicksAfterHitToCheck: 10
  DontCheckLaggyPeople: false
  MinimumKnockbackCheck: 0.1
  LowKnockbackValues: 0.35
  AmountMoved: 1.0
  DontCheckOnWalls: true
  KnockbackCommand: kick %PLAYER% antiknockback is not allowed!#broadcast %PLAYER% was kicked for hacking!
  Threshhold: 8
  LowerAmount: 0.6
  DontCheckIfPlayerIsSprinting: false

Specifics:
  #If this option is enabled, players can only use AntiAura commands with the permission node 'AntiAura.command'.
  #Default: false
  CommandPermissions: false
  CrackShotCompatibilityTime: 40
  AutoUpdaterMinutes: -1
  version: 39
  CallFakeLeaveEvent: true
  InvalidChatCommand: ''
  #If this option is enabled, people with permission node 'AntiAura.bypass' bypass all AntiAura checks.
  #Default: false
  EnablePermissions: false
  #If this option is enabled, additional messages are printed in the console when a player is kicked.
  #Default: true
  ShowDebug: true
  EnableTargetblockChecking: false
JoinTeleport: true

Criticals:
  Enabled: false
  BlockPacketCriticalHits: false
  IncreaseThresholdWithPacketCriticals: true
  SafeHitDecrease: 1.5
  Threshhold: 8
  CriticalsCommand: kick %PLAYER% Criticals is not allowed!#broadcast %PLAYER% was kicked for hacking!

FastEat:
  Enabled: false
  Time: 1.5
  BlockIfSpeedTooHigh: true
  MaxEatingTravelSpeed: 1.0
  Threshold: 2
  SafeEatDecrease: 1.0
  FastEatCommand: kick %PLAYER% FastEat is not allowed!#broadcast %PLAYER% was kicked for hacking!

Spambots:
  Captcha:
    Enabled: false
    EnabledOnlyWhenSpammed: true
    NewPlayersOnly: true
    CaptchaCommand: kick %PLAYER% You failed the captcha!
    Message: Please type CAPTCHA to move and type commands!
  MessageDisabling:
    StopChatBeforeMovement: true
    DisableJoinAndLeaveMessages: true

EnableNormalChecks: true

Step:
  Enabled: false
  TimePerCheck: 3
  MaxDistanceMovedUpwards: 1.4
  ForceUserToGround: true
  Threshold: 8
  SingleBlock: false
  StepCommand: kick %PLAYER% Step/FastFlight is not allowed!#broadcast %PLAYER% was kicked for hacking! (Step)

VelocityAccounting:
  AllowBowBoosting: false
  AllowMultipleVelocities: true
  MultipleXZVelocities: true
  UsePlayerVelocity: false
  NormalVelocityLeniency: 1.1
  CombatVelocityLeniency: 2.0

Spider:
  Enabled: false
  MaxHeightOffGround: 1.25
  DragBackThreshold: 0
  Threshold: 5
  SpiderCommand: kick %PLAYER% Spider is not allowed!#broadcast %PLAYER% was kicked for hacking! (Spider)

Flight:
    Enabled: false
    StrictMode: false
    Threshhold: 7
    LowerAmount: 1.0
    ValuePerPotionLevel: 2
    TimeInTheAir: 22
    FlightCommand: kick %PLAYER% Flying is not allowed!#broadcast %PLAYER% was kicked for hacking!

CancelChecksIfPlayerIsTeleportedDistance: 1
DontCheckTime: 1

Speed:
    Enabled: false
    ValuePerPotionLevel: 2
    EfficientCheck: false
    ExemptWhenUsingVelocity: false
    SpeedLeniency: 0.15
    ForceDragbackLeniency: 0.5
    Threshhold: 15
    DragBackThreshold: 10
    LowerAmount: 1.0
    SpeedCommand: kick %PLAYER% SpeedHack is not allowed!#broadcast %PLAYER% was kicked for hacking!
    KeepDirection: false
    MaxSneakingSpeed: 1.25
    Water: true
    DamageHearts: 1.0

Teleport:
   Enable: false
   TeleportCommand: kick %PLAYER% Teleportation is not allowed!#broadcast %PLAYER% was kicked for hacking!
   ForceKick: true
   BlockTeleport: true
   MinTeleportDistance: 12
   Threshold: 5

FastPlace:
  Enabled: false
  Threshold: 5
  MaxBlocksAllowedPerSecond: 5
  BlockPlacingWithHeadMovement: true
  OnlyWithBelowFeet: true
  BlockTower: true
  TowerDistance: 1.5
  MaxTowerPerSec: 2
  FastPlaceCommand: kick %PLAYER% FastPlace is not allowed!#broadcast %PLAYER% was kicked for hacking! (FastPlace)

NoFall:
  Enabled: false
  Threshold: 15
  LeniencyTime: 0
  DragToGround: false
  DamagePlayer: true
  NoFallCommand: kick %PLAYER% NoFall is not allowed!#broadcast %PLAYER% was kicked for hacking! (NoFall)

Phase:
  Enabled: false
  Threshold: 5
  PhaseCommand: kick %PLAYER% Phase is not allowed!#broadcast %PLAYER% was kicked for hacking! (Phase)

FastBreak:
  Enabled: false
  AccuracyCreative: false
  BreakSpeedIgnore: 500
  Threshold: 15
  SafeHitDecrease: 0.4
  MaxSurvivalBlocksPerSecond: 20
  MaxCreativeBlocksPerSecond: 40
  DisableFastBreakOnWood: false
  FastBreakCommand: kick %PLAYER% FastBreak is not allowed!#broadcast %PLAYER% was kicked for hacking! (FastBreak)

NoSwing:
  Enabled: false
  Threshold: 5
  SafeInteractDecrease: 0.5
  SwingLeniency: 3
  NoSwingCommand: kick %PLAYER% NoSwing is not allowed!#broadcast %PLAYER% was kicked for hacking! (NoSwing)

AntiFire:
  Enabled: false
  Threshold: 4
  SafeFireDecrease: 0.1
  AntiFireCommand: kick %PLAYER% AntiFire is not allowed!#broadcast %PLAYER% was kicked for hacking! (AntiFire)

AntiPotion:
  Enabled: false
  Threshold: 1.5
  ReLightPlayer: false
  SafePotionDecrease: 0.05
  AntiPotionCommand: kick %PLAYER% AntiPotion is not allowed!#broadcast %PLAYER% was kicked for hacking! (AntiPotion)

Regen:
  Enabled: false
  MaxHalfHeartsPerRegen: 1.0
  MaxHeartsPerSecond: 5.0
  RegenCommand: kick %PLAYER% Regen is not allowed!#broadcast %PLAYER% was kicked for hacking! (Regen)
  Threshold: 5

Elytra:
  HeightBlockage: true
  DistanceBlockage: true

BowAimbot:
  ArrowVelocity: 1.3
  ArrowsOnly: false

All:
  MinTPS: 15
  StopCrashes: false
  ForceDependencyDownload: false
